// <auto-generated />
using System;
using Desic.EntityFrameworkCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desic.EntityFrameworkCore.Sqlite.Migrations
{
    [DbContext(typeof(DesicContext))]
    [Migration("20260213015959_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Desic.EntityFrameworkCore.Entities.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EntityTypes", "app");
                });

            modelBuilder.Entity("Desic.EntityFrameworkCore.Entities.Iso3166Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("Alpha2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<string>("Alpha3")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<Guid>("DeletedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8);

                    b.Property<Guid>("DeletedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(7);

                    b.Property<int>("IsoId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(11);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.HasIndex("Alpha2")
                        .IsUnique();

                    b.HasIndex("Alpha3")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsoId")
                        .IsUnique();

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("Name");

                    b.ToTable("Iso3166Countries", "ref");
                });

            modelBuilder.Entity("Desic.EntityFrameworkCore.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("Name");

                    b.ToTable("Tags", "app");
                });

            modelBuilder.Entity("Desic.EntityFrameworkCore.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnOrder(8);

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnOrder(9);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "app");
                });

            modelBuilder.Entity("Desic.EntityFrameworkCore.Entities.Iso3166Country", b =>
                {
                    b.HasOne("Desic.EntityFrameworkCore.Entities.EntityType", null)
                        .WithOne()
                        .HasForeignKey("Desic.EntityFrameworkCore.Entities.Iso3166Country", "CreatedByTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Desic.EntityFrameworkCore.Entities.EntityType", null)
                        .WithOne()
                        .HasForeignKey("Desic.EntityFrameworkCore.Entities.Iso3166Country", "ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Desic.EntityFrameworkCore.Entities.Tag", b =>
                {
                    b.HasOne("Desic.EntityFrameworkCore.Entities.EntityType", null)
                        .WithOne()
                        .HasForeignKey("Desic.EntityFrameworkCore.Entities.Tag", "CreatedByTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Desic.EntityFrameworkCore.Entities.EntityType", null)
                        .WithOne()
                        .HasForeignKey("Desic.EntityFrameworkCore.Entities.Tag", "ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Desic.EntityFrameworkCore.Entities.User", b =>
                {
                    b.HasOne("Desic.EntityFrameworkCore.Entities.EntityType", null)
                        .WithOne()
                        .HasForeignKey("Desic.EntityFrameworkCore.Entities.User", "CreatedByTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Desic.EntityFrameworkCore.Entities.EntityType", null)
                        .WithOne()
                        .HasForeignKey("Desic.EntityFrameworkCore.Entities.User", "ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
