// <auto-generated />
using System;
using Desic.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desic.Infrastructure.Data.SqlServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desic.Domain.EntityTypes.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EntityTypes", "ref");
                });

            modelBuilder.Entity("Desic.Domain.Iso3166Countries.Iso3166Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<string>("Alpha2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnOrder(15);

                    b.Property<string>("Alpha3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnOrder(16);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("DeletedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.Property<bool>("IsBeingSeeded")
                        .HasColumnType("bit")
                        .HasColumnOrder(13);

                    b.Property<int>("IsoId")
                        .HasColumnType("int")
                        .HasColumnOrder(14);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(5);

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(17);

                    b.HasKey("Id");

                    b.HasIndex("Alpha2")
                        .IsUnique();

                    b.HasIndex("Alpha3")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("IsBeingSeeded");

                    b.HasIndex("IsoId")
                        .IsUnique();

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("ModifiedOn");

                    b.HasIndex("Name");

                    b.ToTable("Iso3166Countries", "ref");
                });

            modelBuilder.Entity("Desic.Domain.Labels.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("DeletedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(5);

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnOrder(13);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("ModifiedOn");

                    b.HasIndex("Name");

                    b.ToTable("Labels", "app");
                });

            modelBuilder.Entity("Desic.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("DeletedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(5);

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnOrder(13);

                    b.Property<string>("Value")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("ModifiedOn");

                    b.HasIndex("Name");

                    b.HasIndex("Value");

                    b.ToTable("Tags", "app");
                });

            modelBuilder.Entity("Desic.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("DeletedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(12);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(14);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(5);

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(13);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("ModifiedOn");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "app");
                });

            modelBuilder.Entity("Desic.Domain.Iso3166Countries.Iso3166Country", b =>
                {
                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("DeletedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Desic.Domain.Labels.Label", b =>
                {
                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("DeletedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Desic.Domain.Tags.Tag", b =>
                {
                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("DeletedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Desic.Domain.Users.User", b =>
                {
                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("DeletedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
