services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "4be55771-1b77-41ef-9a98-6c5d1774fbf9"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver_data:/var/opt/mssql

  desic.api:
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionString:Sqlite=Data Source=/app/data/desic.db;
      - ConnectionStrings:SqlServer=Server=sqlserver;Database=Desic;User Id=sa;Password=4be55771-1b77-41ef-9a98-6c5d1774fbf9;TrustServerCertificate=True
      - DbProvider=SqlServer
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - sqlite_data:/app/data

  desic.web:
    command: sh -c "npm run dev"
    environment:
      - NODE_ENV=development
    ports:
      - "56054:56054"
    volumes:
      - ./source/Desic.Web:/app # mounts local project directory to the container's working directory
      - /app/node_modules # creates an anonymous volume to prevent host's node_modules from overwriting container's

volumes:
  sqlite_data:
  sqlserver_data: