services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile

  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: src/web
      dockerfile: Dockerfile
    command: sh -c "npm start"
    depends_on:
      - api
