services:
  desic.api:
    image: ${DOCKER_REGISTRY-}desicapi
    build:
      context: .
      dockerfile: source/Desic.Api/Dockerfile

  desic.web:
    image: ${DOCKER_REGISTRY-}desicweb
    build:
      context: source/Desic.Web
      dockerfile: Dockerfile
    command: sh -c "npm start"
    depends_on:
      - desic.api
