services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${DB_PASSWORD_INIT}"
      MSSQL_PID: "Developer"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", "${DB_USER_INIT}", "-P", "${DB_PASSWORD_INIT}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
    volumes:
      - sqlserver_data:/var/opt/mssql

  desic.databaseupdater:
    image: ${DOCKER_REGISTRY-}desicdatabaseupdater
    build:
      context: .
      dockerfile: src/Desic.DatabaseUpdater/Dockerfile
    command: ["--provider", "SqlServer", "--connection-init", "${CONNECTION_STRINGS_SQLSERVER_INIT}", "--connection", "${CONNECTION_STRINGS_SQLSERVER_MIGRATIONS}"]
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: "no"

  desic.api:
    depends_on:
      desic.databaseupdater:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings:Sqlite=${CONNECTION_STRINGS_SQLITE}
      - ConnectionStrings:SqlServer=${CONNECTION_STRINGS_SQLSERVER_API}
      - DbProvider=SqlServer
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - sqlite_data:/app/data

  desic.web:
    command: sh -c "npm run dev"
    environment:
      - NODE_ENV=development
    ports:
      - "56054:56054"
    volumes:
      - ./src/Desic.Web:/app # mounts local project directory to the container's working directory
      - /app/node_modules # creates an anonymous volume to prevent host's node_modules from overwriting container's

volumes:
  sqlite_data:
  sqlserver_data: