services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile

  desic.web:
    image: ${DOCKER_REGISTRY-}desicweb
    build:
      context: src/Desic.Web
      dockerfile: Dockerfile
    command: sh -c "npm start"
    depends_on:
      - api
