// <auto-generated />
using System;
using Desic.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desic.Infrastructure.Data.Sqlite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Desic.Domain.EntityTypes.EntityType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EntityTypes", (string)null);
                });

            modelBuilder.Entity("Desic.Domain.Iso3166Countries.Iso3166Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("Alpha2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(15);

                    b.Property<string>("Alpha3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(16);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("DeletedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<bool>("IsBeingSeeded")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(13);

                    b.Property<int>("IsoId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(14);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(17);

                    b.HasKey("Id");

                    b.HasIndex("Alpha2");

                    b.HasIndex("Alpha3");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("IsBeingSeeded");

                    b.HasIndex("IsoId")
                        .IsUnique();

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("ModifiedOn");

                    b.HasIndex("Name");

                    b.ToTable("Iso3166Countries", (string)null);
                });

            modelBuilder.Entity("Desic.Domain.Labels.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("DeletedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("ModifiedOn");

                    b.HasIndex("Name");

                    b.ToTable("Labels", (string)null);
                });

            modelBuilder.Entity("Desic.Domain.Processes.Process", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("DeletedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<DateTime?>("FaileddOn")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(15);

                    b.Property<string>("Message")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(17);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(16);

                    b.Property<DateTime?>("StartedOn")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.HasKey("Id");

                    b.HasIndex("CompletedOn");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("FaileddOn");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("ModifiedOn");

                    b.HasIndex("Name");

                    b.HasIndex("StartedOn");

                    b.ToTable("Processes", (string)null);
                });

            modelBuilder.Entity("Desic.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("DeletedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.Property<string>("Value")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("ModifiedOn");

                    b.HasIndex("Name");

                    b.HasIndex("Value");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Desic.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<Guid>("CreatedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(4)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(9);

                    b.Property<string>("DeletedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(10);

                    b.Property<Guid?>("DeletedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(11);

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(12);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnOrder(14);

                    b.Property<Guid>("ModifiedById")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(5);

                    b.Property<string>("ModifiedByName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.Property<Guid>("ModifiedByTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(8)
                        .HasDefaultValueSql("DATETIME('now')");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnOrder(13);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatedByTypeId");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DeletedById");

                    b.HasIndex("DeletedByTypeId");

                    b.HasIndex("DeletedOn");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ModifiedByTypeId");

                    b.HasIndex("ModifiedOn");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Desic.Domain.Iso3166Countries.Iso3166Country", b =>
                {
                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("DeletedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Desic.Domain.Labels.Label", b =>
                {
                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("DeletedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Desic.Domain.Processes.Process", b =>
                {
                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("DeletedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Desic.Domain.Tags.Tag", b =>
                {
                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("DeletedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Desic.Domain.Users.User", b =>
                {
                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("DeletedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Desic.Domain.EntityTypes.EntityType", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
