// use top right drop down to set desired environment

GET {{HostAddressApi}}/v1/healthz/live
Accept: text/plain

###

GET {{HostAddressApi}}/v1/healthz/ready
Accept: text/plain

###

GET {{HostAddressApi}}/v1/healthz/report
Accept: application/json

### Entity Types

GET {{HostAddressApi}}/v1/entitytypes
Accept: application/json

### Entity Types

GET {{HostAddressApi}}/v1/entitytypes?orderBy=Name&asc=false&orderBy=Key&asc=false
Accept: application/json

###

GET {{HostAddressApi}}/v1/entitytypes?includeTotalCount=true&startIndex=1&count=2&orderBy=Key&asc=false
Accept: application/json

###

GET {{HostAddressApi}}/v1/entitytypes?name=Label
Accept: application/json

### Iso 3166 Countries

GET {{HostAddressApi}}/v1/iso3166countries
Accept: application/json

###

GET {{HostAddressApi}}/v1/iso3166countries?includeTotalCount=true&startIndex=1&count=2&orderingMethod=alpha2Desc
Accept: application/json

###

GET {{HostAddressApi}}/v1/iso3166countries?namecontains=states
Accept: application/json

### Users

GET {{HostAddressApi}}/v1/users/00000005-000F-0000-0000-000000000001
Accept: application/json

###

POST {{HostAddressApi}}/v1/users/
Accept: application/json
Content-Type: application/json
Prefer: return=representation

{
  "username": "test-user-pr-{{$datetime "yyyyMMddhhmmss"}}"
}

###

POST {{HostAddressApi}}/v1/users/
Accept: application/json
Content-Type: application/json

{
  "username": "test-user-pm-{{$datetime "yyyyMMddhhmmss"}}"
}

###

POST {{HostAddressApi}}/v1/users/
Accept: application/json
Content-Type: application/json

{
  "username": "invalid username"
}