// use top right drop down to set desired environment

GET {{HostAddressApi}}/v1/healthz/live
Accept: text/plain

###

GET {{HostAddressApi}}/v1/healthz/ready
Accept: text/plain

###

GET {{HostAddressApi}}/v1/healthz/report
Accept: application/json

###

GET {{HostAddressApi}}/v1/entitytypes?startIndex=1&count=3
Accept: application/json

###

GET {{HostAddressApi}}/v1/users/00000005-0000-0000-0000-000000000001
Accept: application/json

###

POST {{HostAddressApi}}/v1/users/
Accept: application/json
Content-Type: application/json
Prefer: return=representation

{
  "username": "test-user-pr-{{$datetime "yyyyMMddhhmmss"}}"
}

###

POST {{HostAddressApi}}/v1/users/
Accept: application/json
Content-Type: application/json

{
  "username": "test-user-pm-{{$datetime "yyyyMMddhhmmss"}}"
}

###

POST {{HostAddressApi}}/v1/users/
Accept: application/json
Content-Type: application/json

{
  "username": "invalid username"
}