@Api_HostAddress = http://localhost:5029

GET {{Api_HostAddress}}/v1/healthz/live
Accept: text/plain

###

GET {{Api_HostAddress}}/v1/healthz/ready
Accept: text/plain

###

GET {{Api_HostAddress}}/v1/healthz/report
Accept: application/json

###

GET {{Api_HostAddress}}/v1/users/00000004-0000-0000-0000-000000000001
Accept: application/json