namespace Desic.Core.Iso3166Countries;

[Obsolete("These are currently loaded using seeding")]
internal static class Iso3166Countries
{
    /* data in Generate() is accurate to: 2026-02-10
       source: https://github.com/stefangabos/world_countries/blob/b5e709843d7a26eda25ece4e4cb8192dcb31b3d3/data/countries/en/world.xml
       perform following modifications to quickly translate the xml data to the c# model format below
           note: do not include the first or last ' character in the replaces below, those are just to designate where to start and end (non-inclusive)
           1) remove lines 1, 2 and the last line (xml and countries opening and closing tags)
           2)                    replace '    <country id'     with     '            new Country { IsoId '
           3)                    replace '="'                  with     '= "'
           4)                    replace ' alpha2='            with     ', Alpha2 ='
           5)                    replace ' alpha3='            with     ', Alpha3 ='
           6)                    replace ' name='              with     ', Name ='
           7)                    replace '/>'                  with     ' },'
           8) regular expression replace '"(\d+)"'             with     '$1'
           9) on last line (only) remove the comma at the end of the line
    */
    internal static Iso3166Country[] Generate()
    {
        return
        [
            new Iso3166Country { IsoId = 4, Alpha2 = "af", Alpha3 = "afg", Name = "Afghanistan" },
            new Iso3166Country { IsoId = 248, Alpha2 = "ax", Alpha3 = "ala", Name = "Åland Islands" },
            new Iso3166Country { IsoId = 8, Alpha2 = "al", Alpha3 = "alb", Name = "Albania" },
            new Iso3166Country { IsoId = 12, Alpha2 = "dz", Alpha3 = "dza", Name = "Algeria" },
            new Iso3166Country { IsoId = 16, Alpha2 = "as", Alpha3 = "asm", Name = "American Samoa" },
            new Iso3166Country { IsoId = 20, Alpha2 = "ad", Alpha3 = "and", Name = "Andorra" },
            new Iso3166Country { IsoId = 24, Alpha2 = "ao", Alpha3 = "ago", Name = "Angola" },
            new Iso3166Country { IsoId = 660, Alpha2 = "ai", Alpha3 = "aia", Name = "Anguilla" },
            new Iso3166Country { IsoId = 10, Alpha2 = "aq", Alpha3 = "ata", Name = "Antarctica" },
            new Iso3166Country { IsoId = 28, Alpha2 = "ag", Alpha3 = "atg", Name = "Antigua and Barbuda" },
            new Iso3166Country { IsoId = 32, Alpha2 = "ar", Alpha3 = "arg", Name = "Argentina" },
            new Iso3166Country { IsoId = 51, Alpha2 = "am", Alpha3 = "arm", Name = "Armenia" },
            new Iso3166Country { IsoId = 533, Alpha2 = "aw", Alpha3 = "abw", Name = "Aruba" },
            new Iso3166Country { IsoId = 36, Alpha2 = "au", Alpha3 = "aus", Name = "Australia" },
            new Iso3166Country { IsoId = 40, Alpha2 = "at", Alpha3 = "aut", Name = "Austria" },
            new Iso3166Country { IsoId = 31, Alpha2 = "az", Alpha3 = "aze", Name = "Azerbaijan" },
            new Iso3166Country { IsoId = 44, Alpha2 = "bs", Alpha3 = "bhs", Name = "Bahamas" },
            new Iso3166Country { IsoId = 48, Alpha2 = "bh", Alpha3 = "bhr", Name = "Bahrain" },
            new Iso3166Country { IsoId = 50, Alpha2 = "bd", Alpha3 = "bgd", Name = "Bangladesh" },
            new Iso3166Country { IsoId = 52, Alpha2 = "bb", Alpha3 = "brb", Name = "Barbados" },
            new Iso3166Country { IsoId = 112, Alpha2 = "by", Alpha3 = "blr", Name = "Belarus" },
            new Iso3166Country { IsoId = 56, Alpha2 = "be", Alpha3 = "bel", Name = "Belgium" },
            new Iso3166Country { IsoId = 84, Alpha2 = "bz", Alpha3 = "blz", Name = "Belize" },
            new Iso3166Country { IsoId = 204, Alpha2 = "bj", Alpha3 = "ben", Name = "Benin" },
            new Iso3166Country { IsoId = 60, Alpha2 = "bm", Alpha3 = "bmu", Name = "Bermuda" },
            new Iso3166Country { IsoId = 64, Alpha2 = "bt", Alpha3 = "btn", Name = "Bhutan" },
            new Iso3166Country { IsoId = 68, Alpha2 = "bo", Alpha3 = "bol", Name = "Bolivia, Plurinational State of" },
            new Iso3166Country { IsoId = 535, Alpha2 = "bq", Alpha3 = "bes", Name = "Bonaire, Sint Eustatius and Saba" },
            new Iso3166Country { IsoId = 70, Alpha2 = "ba", Alpha3 = "bih", Name = "Bosnia and Herzegovina" },
            new Iso3166Country { IsoId = 72, Alpha2 = "bw", Alpha3 = "bwa", Name = "Botswana" },
            new Iso3166Country { IsoId = 74, Alpha2 = "bv", Alpha3 = "bvt", Name = "Bouvet Island" },
            new Iso3166Country { IsoId = 76, Alpha2 = "br", Alpha3 = "bra", Name = "Brazil" },
            new Iso3166Country { IsoId = 86, Alpha2 = "io", Alpha3 = "iot", Name = "British Indian Ocean Territory" },
            new Iso3166Country { IsoId = 96, Alpha2 = "bn", Alpha3 = "brn", Name = "Brunei Darussalam" },
            new Iso3166Country { IsoId = 100, Alpha2 = "bg", Alpha3 = "bgr", Name = "Bulgaria" },
            new Iso3166Country { IsoId = 854, Alpha2 = "bf", Alpha3 = "bfa", Name = "Burkina Faso" },
            new Iso3166Country { IsoId = 108, Alpha2 = "bi", Alpha3 = "bdi", Name = "Burundi" },
            new Iso3166Country { IsoId = 132, Alpha2 = "cv", Alpha3 = "cpv", Name = "Cabo Verde" },
            new Iso3166Country { IsoId = 116, Alpha2 = "kh", Alpha3 = "khm", Name = "Cambodia" },
            new Iso3166Country { IsoId = 120, Alpha2 = "cm", Alpha3 = "cmr", Name = "Cameroon" },
            new Iso3166Country { IsoId = 124, Alpha2 = "ca", Alpha3 = "can", Name = "Canada" },
            new Iso3166Country { IsoId = 136, Alpha2 = "ky", Alpha3 = "cym", Name = "Cayman Islands" },
            new Iso3166Country { IsoId = 140, Alpha2 = "cf", Alpha3 = "caf", Name = "Central African Republic" },
            new Iso3166Country { IsoId = 148, Alpha2 = "td", Alpha3 = "tcd", Name = "Chad" },
            new Iso3166Country { IsoId = 152, Alpha2 = "cl", Alpha3 = "chl", Name = "Chile" },
            new Iso3166Country { IsoId = 156, Alpha2 = "cn", Alpha3 = "chn", Name = "China" },
            new Iso3166Country { IsoId = 162, Alpha2 = "cx", Alpha3 = "cxr", Name = "Christmas Island" },
            new Iso3166Country { IsoId = 166, Alpha2 = "cc", Alpha3 = "cck", Name = "Cocos (Keeling) Islands" },
            new Iso3166Country { IsoId = 170, Alpha2 = "co", Alpha3 = "col", Name = "Colombia" },
            new Iso3166Country { IsoId = 174, Alpha2 = "km", Alpha3 = "com", Name = "Comoros" },
            new Iso3166Country { IsoId = 178, Alpha2 = "cg", Alpha3 = "cog", Name = "Congo" },
            new Iso3166Country { IsoId = 180, Alpha2 = "cd", Alpha3 = "cod", Name = "Congo, Democratic Republic of the" },
            new Iso3166Country { IsoId = 184, Alpha2 = "ck", Alpha3 = "cok", Name = "Cook Islands" },
            new Iso3166Country { IsoId = 188, Alpha2 = "cr", Alpha3 = "cri", Name = "Costa Rica" },
            new Iso3166Country { IsoId = 384, Alpha2 = "ci", Alpha3 = "civ", Name = "Côte d'Ivoire" },
            new Iso3166Country { IsoId = 191, Alpha2 = "hr", Alpha3 = "hrv", Name = "Croatia" },
            new Iso3166Country { IsoId = 192, Alpha2 = "cu", Alpha3 = "cub", Name = "Cuba" },
            new Iso3166Country { IsoId = 531, Alpha2 = "cw", Alpha3 = "cuw", Name = "Curaçao" },
            new Iso3166Country { IsoId = 196, Alpha2 = "cy", Alpha3 = "cyp", Name = "Cyprus" },
            new Iso3166Country { IsoId = 203, Alpha2 = "cz", Alpha3 = "cze", Name = "Czechia" },
            new Iso3166Country { IsoId = 208, Alpha2 = "dk", Alpha3 = "dnk", Name = "Denmark" },
            new Iso3166Country { IsoId = 262, Alpha2 = "dj", Alpha3 = "dji", Name = "Djibouti" },
            new Iso3166Country { IsoId = 212, Alpha2 = "dm", Alpha3 = "dma", Name = "Dominica" },
            new Iso3166Country { IsoId = 214, Alpha2 = "do", Alpha3 = "dom", Name = "Dominican Republic" },
            new Iso3166Country { IsoId = 218, Alpha2 = "ec", Alpha3 = "ecu", Name = "Ecuador" },
            new Iso3166Country { IsoId = 818, Alpha2 = "eg", Alpha3 = "egy", Name = "Egypt" },
            new Iso3166Country { IsoId = 222, Alpha2 = "sv", Alpha3 = "slv", Name = "El Salvador" },
            new Iso3166Country { IsoId = 226, Alpha2 = "gq", Alpha3 = "gnq", Name = "Equatorial Guinea" },
            new Iso3166Country { IsoId = 232, Alpha2 = "er", Alpha3 = "eri", Name = "Eritrea" },
            new Iso3166Country { IsoId = 233, Alpha2 = "ee", Alpha3 = "est", Name = "Estonia" },
            new Iso3166Country { IsoId = 748, Alpha2 = "sz", Alpha3 = "swz", Name = "Eswatini" },
            new Iso3166Country { IsoId = 231, Alpha2 = "et", Alpha3 = "eth", Name = "Ethiopia" },
            new Iso3166Country { IsoId = 238, Alpha2 = "fk", Alpha3 = "flk", Name = "Falkland Islands (Malvinas)" },
            new Iso3166Country { IsoId = 234, Alpha2 = "fo", Alpha3 = "fro", Name = "Faroe Islands" },
            new Iso3166Country { IsoId = 242, Alpha2 = "fj", Alpha3 = "fji", Name = "Fiji" },
            new Iso3166Country { IsoId = 246, Alpha2 = "fi", Alpha3 = "fin", Name = "Finland" },
            new Iso3166Country { IsoId = 250, Alpha2 = "fr", Alpha3 = "fra", Name = "France" },
            new Iso3166Country { IsoId = 254, Alpha2 = "gf", Alpha3 = "guf", Name = "French Guiana" },
            new Iso3166Country { IsoId = 258, Alpha2 = "pf", Alpha3 = "pyf", Name = "French Polynesia" },
            new Iso3166Country { IsoId = 260, Alpha2 = "tf", Alpha3 = "atf", Name = "French Southern Territories" },
            new Iso3166Country { IsoId = 266, Alpha2 = "ga", Alpha3 = "gab", Name = "Gabon" },
            new Iso3166Country { IsoId = 270, Alpha2 = "gm", Alpha3 = "gmb", Name = "Gambia" },
            new Iso3166Country { IsoId = 268, Alpha2 = "ge", Alpha3 = "geo", Name = "Georgia" },
            new Iso3166Country { IsoId = 276, Alpha2 = "de", Alpha3 = "deu", Name = "Germany" },
            new Iso3166Country { IsoId = 288, Alpha2 = "gh", Alpha3 = "gha", Name = "Ghana" },
            new Iso3166Country { IsoId = 292, Alpha2 = "gi", Alpha3 = "gib", Name = "Gibraltar" },
            new Iso3166Country { IsoId = 300, Alpha2 = "gr", Alpha3 = "grc", Name = "Greece" },
            new Iso3166Country { IsoId = 304, Alpha2 = "gl", Alpha3 = "grl", Name = "Greenland" },
            new Iso3166Country { IsoId = 308, Alpha2 = "gd", Alpha3 = "grd", Name = "Grenada" },
            new Iso3166Country { IsoId = 312, Alpha2 = "gp", Alpha3 = "glp", Name = "Guadeloupe" },
            new Iso3166Country { IsoId = 316, Alpha2 = "gu", Alpha3 = "gum", Name = "Guam" },
            new Iso3166Country { IsoId = 320, Alpha2 = "gt", Alpha3 = "gtm", Name = "Guatemala" },
            new Iso3166Country { IsoId = 831, Alpha2 = "gg", Alpha3 = "ggy", Name = "Guernsey" },
            new Iso3166Country { IsoId = 324, Alpha2 = "gn", Alpha3 = "gin", Name = "Guinea" },
            new Iso3166Country { IsoId = 624, Alpha2 = "gw", Alpha3 = "gnb", Name = "Guinea-Bissau" },
            new Iso3166Country { IsoId = 328, Alpha2 = "gy", Alpha3 = "guy", Name = "Guyana" },
            new Iso3166Country { IsoId = 332, Alpha2 = "ht", Alpha3 = "hti", Name = "Haiti" },
            new Iso3166Country { IsoId = 334, Alpha2 = "hm", Alpha3 = "hmd", Name = "Heard Island and McDonald Islands" },
            new Iso3166Country { IsoId = 336, Alpha2 = "va", Alpha3 = "vat", Name = "Holy See" },
            new Iso3166Country { IsoId = 340, Alpha2 = "hn", Alpha3 = "hnd", Name = "Honduras" },
            new Iso3166Country { IsoId = 344, Alpha2 = "hk", Alpha3 = "hkg", Name = "Hong Kong" },
            new Iso3166Country { IsoId = 348, Alpha2 = "hu", Alpha3 = "hun", Name = "Hungary" },
            new Iso3166Country { IsoId = 352, Alpha2 = "is", Alpha3 = "isl", Name = "Iceland" },
            new Iso3166Country { IsoId = 356, Alpha2 = "in", Alpha3 = "ind", Name = "India" },
            new Iso3166Country { IsoId = 360, Alpha2 = "id", Alpha3 = "idn", Name = "Indonesia" },
            new Iso3166Country { IsoId = 364, Alpha2 = "ir", Alpha3 = "irn", Name = "Iran, Islamic Republic of" },
            new Iso3166Country { IsoId = 368, Alpha2 = "iq", Alpha3 = "irq", Name = "Iraq" },
            new Iso3166Country { IsoId = 372, Alpha2 = "ie", Alpha3 = "irl", Name = "Ireland" },
            new Iso3166Country { IsoId = 833, Alpha2 = "im", Alpha3 = "imn", Name = "Isle of Man" },
            new Iso3166Country { IsoId = 376, Alpha2 = "il", Alpha3 = "isr", Name = "Israel" },
            new Iso3166Country { IsoId = 380, Alpha2 = "it", Alpha3 = "ita", Name = "Italy" },
            new Iso3166Country { IsoId = 388, Alpha2 = "jm", Alpha3 = "jam", Name = "Jamaica" },
            new Iso3166Country { IsoId = 392, Alpha2 = "jp", Alpha3 = "jpn", Name = "Japan" },
            new Iso3166Country { IsoId = 832, Alpha2 = "je", Alpha3 = "jey", Name = "Jersey" },
            new Iso3166Country { IsoId = 400, Alpha2 = "jo", Alpha3 = "jor", Name = "Jordan" },
            new Iso3166Country { IsoId = 398, Alpha2 = "kz", Alpha3 = "kaz", Name = "Kazakhstan" },
            new Iso3166Country { IsoId = 404, Alpha2 = "ke", Alpha3 = "ken", Name = "Kenya" },
            new Iso3166Country { IsoId = 296, Alpha2 = "ki", Alpha3 = "kir", Name = "Kiribati" },
            new Iso3166Country { IsoId = 408, Alpha2 = "kp", Alpha3 = "prk", Name = "Korea, Democratic People's Republic of" },
            new Iso3166Country { IsoId = 410, Alpha2 = "kr", Alpha3 = "kor", Name = "Korea, Republic of" },
            new Iso3166Country { IsoId = 414, Alpha2 = "kw", Alpha3 = "kwt", Name = "Kuwait" },
            new Iso3166Country { IsoId = 417, Alpha2 = "kg", Alpha3 = "kgz", Name = "Kyrgyzstan" },
            new Iso3166Country { IsoId = 418, Alpha2 = "la", Alpha3 = "lao", Name = "Lao People's Democratic Republic" },
            new Iso3166Country { IsoId = 428, Alpha2 = "lv", Alpha3 = "lva", Name = "Latvia" },
            new Iso3166Country { IsoId = 422, Alpha2 = "lb", Alpha3 = "lbn", Name = "Lebanon" },
            new Iso3166Country { IsoId = 426, Alpha2 = "ls", Alpha3 = "lso", Name = "Lesotho" },
            new Iso3166Country { IsoId = 430, Alpha2 = "lr", Alpha3 = "lbr", Name = "Liberia" },
            new Iso3166Country { IsoId = 434, Alpha2 = "ly", Alpha3 = "lby", Name = "Libya" },
            new Iso3166Country { IsoId = 438, Alpha2 = "li", Alpha3 = "lie", Name = "Liechtenstein" },
            new Iso3166Country { IsoId = 440, Alpha2 = "lt", Alpha3 = "ltu", Name = "Lithuania" },
            new Iso3166Country { IsoId = 442, Alpha2 = "lu", Alpha3 = "lux", Name = "Luxembourg" },
            new Iso3166Country { IsoId = 446, Alpha2 = "mo", Alpha3 = "mac", Name = "Macao" },
            new Iso3166Country { IsoId = 450, Alpha2 = "mg", Alpha3 = "mdg", Name = "Madagascar" },
            new Iso3166Country { IsoId = 454, Alpha2 = "mw", Alpha3 = "mwi", Name = "Malawi" },
            new Iso3166Country { IsoId = 458, Alpha2 = "my", Alpha3 = "mys", Name = "Malaysia" },
            new Iso3166Country { IsoId = 462, Alpha2 = "mv", Alpha3 = "mdv", Name = "Maldives" },
            new Iso3166Country { IsoId = 466, Alpha2 = "ml", Alpha3 = "mli", Name = "Mali" },
            new Iso3166Country { IsoId = 470, Alpha2 = "mt", Alpha3 = "mlt", Name = "Malta" },
            new Iso3166Country { IsoId = 584, Alpha2 = "mh", Alpha3 = "mhl", Name = "Marshall Islands" },
            new Iso3166Country { IsoId = 474, Alpha2 = "mq", Alpha3 = "mtq", Name = "Martinique" },
            new Iso3166Country { IsoId = 478, Alpha2 = "mr", Alpha3 = "mrt", Name = "Mauritania" },
            new Iso3166Country { IsoId = 480, Alpha2 = "mu", Alpha3 = "mus", Name = "Mauritius" },
            new Iso3166Country { IsoId = 175, Alpha2 = "yt", Alpha3 = "myt", Name = "Mayotte" },
            new Iso3166Country { IsoId = 484, Alpha2 = "mx", Alpha3 = "mex", Name = "Mexico" },
            new Iso3166Country { IsoId = 583, Alpha2 = "fm", Alpha3 = "fsm", Name = "Micronesia, Federated States of" },
            new Iso3166Country { IsoId = 498, Alpha2 = "md", Alpha3 = "mda", Name = "Moldova, Republic of" },
            new Iso3166Country { IsoId = 492, Alpha2 = "mc", Alpha3 = "mco", Name = "Monaco" },
            new Iso3166Country { IsoId = 496, Alpha2 = "mn", Alpha3 = "mng", Name = "Mongolia" },
            new Iso3166Country { IsoId = 499, Alpha2 = "me", Alpha3 = "mne", Name = "Montenegro" },
            new Iso3166Country { IsoId = 500, Alpha2 = "ms", Alpha3 = "msr", Name = "Montserrat" },
            new Iso3166Country { IsoId = 504, Alpha2 = "ma", Alpha3 = "mar", Name = "Morocco" },
            new Iso3166Country { IsoId = 508, Alpha2 = "mz", Alpha3 = "moz", Name = "Mozambique" },
            new Iso3166Country { IsoId = 104, Alpha2 = "mm", Alpha3 = "mmr", Name = "Myanmar" },
            new Iso3166Country { IsoId = 516, Alpha2 = "na", Alpha3 = "nam", Name = "Namibia" },
            new Iso3166Country { IsoId = 520, Alpha2 = "nr", Alpha3 = "nru", Name = "Nauru" },
            new Iso3166Country { IsoId = 524, Alpha2 = "np", Alpha3 = "npl", Name = "Nepal" },
            new Iso3166Country { IsoId = 528, Alpha2 = "nl", Alpha3 = "nld", Name = "Netherlands" },
            new Iso3166Country { IsoId = 540, Alpha2 = "nc", Alpha3 = "ncl", Name = "New Caledonia" },
            new Iso3166Country { IsoId = 554, Alpha2 = "nz", Alpha3 = "nzl", Name = "New Zealand" },
            new Iso3166Country { IsoId = 558, Alpha2 = "ni", Alpha3 = "nic", Name = "Nicaragua" },
            new Iso3166Country { IsoId = 562, Alpha2 = "ne", Alpha3 = "ner", Name = "Niger" },
            new Iso3166Country { IsoId = 566, Alpha2 = "ng", Alpha3 = "nga", Name = "Nigeria" },
            new Iso3166Country { IsoId = 570, Alpha2 = "nu", Alpha3 = "niu", Name = "Niue" },
            new Iso3166Country { IsoId = 574, Alpha2 = "nf", Alpha3 = "nfk", Name = "Norfolk Island" },
            new Iso3166Country { IsoId = 807, Alpha2 = "mk", Alpha3 = "mkd", Name = "North Macedonia" },
            new Iso3166Country { IsoId = 580, Alpha2 = "mp", Alpha3 = "mnp", Name = "Northern Mariana Islands" },
            new Iso3166Country { IsoId = 578, Alpha2 = "no", Alpha3 = "nor", Name = "Norway" },
            new Iso3166Country { IsoId = 512, Alpha2 = "om", Alpha3 = "omn", Name = "Oman" },
            new Iso3166Country { IsoId = 586, Alpha2 = "pk", Alpha3 = "pak", Name = "Pakistan" },
            new Iso3166Country { IsoId = 585, Alpha2 = "pw", Alpha3 = "plw", Name = "Palau" },
            new Iso3166Country { IsoId = 275, Alpha2 = "ps", Alpha3 = "pse", Name = "Palestine, State of" },
            new Iso3166Country { IsoId = 591, Alpha2 = "pa", Alpha3 = "pan", Name = "Panama" },
            new Iso3166Country { IsoId = 598, Alpha2 = "pg", Alpha3 = "png", Name = "Papua New Guinea" },
            new Iso3166Country { IsoId = 600, Alpha2 = "py", Alpha3 = "pry", Name = "Paraguay" },
            new Iso3166Country { IsoId = 604, Alpha2 = "pe", Alpha3 = "per", Name = "Peru" },
            new Iso3166Country { IsoId = 608, Alpha2 = "ph", Alpha3 = "phl", Name = "Philippines" },
            new Iso3166Country { IsoId = 612, Alpha2 = "pn", Alpha3 = "pcn", Name = "Pitcairn" },
            new Iso3166Country { IsoId = 616, Alpha2 = "pl", Alpha3 = "pol", Name = "Poland" },
            new Iso3166Country { IsoId = 620, Alpha2 = "pt", Alpha3 = "prt", Name = "Portugal" },
            new Iso3166Country { IsoId = 630, Alpha2 = "pr", Alpha3 = "pri", Name = "Puerto Rico" },
            new Iso3166Country { IsoId = 634, Alpha2 = "qa", Alpha3 = "qat", Name = "Qatar" },
            new Iso3166Country { IsoId = 638, Alpha2 = "re", Alpha3 = "reu", Name = "Réunion" },
            new Iso3166Country { IsoId = 642, Alpha2 = "ro", Alpha3 = "rou", Name = "Romania" },
            new Iso3166Country { IsoId = 643, Alpha2 = "ru", Alpha3 = "rus", Name = "Russian Federation" },
            new Iso3166Country { IsoId = 646, Alpha2 = "rw", Alpha3 = "rwa", Name = "Rwanda" },
            new Iso3166Country { IsoId = 652, Alpha2 = "bl", Alpha3 = "blm", Name = "Saint Barthélemy" },
            new Iso3166Country { IsoId = 654, Alpha2 = "sh", Alpha3 = "shn", Name = "Saint Helena, Ascension and Tristan da Cunha" },
            new Iso3166Country { IsoId = 659, Alpha2 = "kn", Alpha3 = "kna", Name = "Saint Kitts and Nevis" },
            new Iso3166Country { IsoId = 662, Alpha2 = "lc", Alpha3 = "lca", Name = "Saint Lucia" },
            new Iso3166Country { IsoId = 663, Alpha2 = "mf", Alpha3 = "maf", Name = "Saint Martin (French part)" },
            new Iso3166Country { IsoId = 666, Alpha2 = "pm", Alpha3 = "spm", Name = "Saint Pierre and Miquelon" },
            new Iso3166Country { IsoId = 670, Alpha2 = "vc", Alpha3 = "vct", Name = "Saint Vincent and the Grenadines" },
            new Iso3166Country { IsoId = 882, Alpha2 = "ws", Alpha3 = "wsm", Name = "Samoa" },
            new Iso3166Country { IsoId = 674, Alpha2 = "sm", Alpha3 = "smr", Name = "San Marino" },
            new Iso3166Country { IsoId = 678, Alpha2 = "st", Alpha3 = "stp", Name = "Sao Tome and Principe" },
            new Iso3166Country { IsoId = 682, Alpha2 = "sa", Alpha3 = "sau", Name = "Saudi Arabia" },
            new Iso3166Country { IsoId = 686, Alpha2 = "sn", Alpha3 = "sen", Name = "Senegal" },
            new Iso3166Country { IsoId = 688, Alpha2 = "rs", Alpha3 = "srb", Name = "Serbia" },
            new Iso3166Country { IsoId = 690, Alpha2 = "sc", Alpha3 = "syc", Name = "Seychelles" },
            new Iso3166Country { IsoId = 694, Alpha2 = "sl", Alpha3 = "sle", Name = "Sierra Leone" },
            new Iso3166Country { IsoId = 702, Alpha2 = "sg", Alpha3 = "sgp", Name = "Singapore" },
            new Iso3166Country { IsoId = 534, Alpha2 = "sx", Alpha3 = "sxm", Name = "Sint Maarten (Dutch part)" },
            new Iso3166Country { IsoId = 703, Alpha2 = "sk", Alpha3 = "svk", Name = "Slovakia" },
            new Iso3166Country { IsoId = 705, Alpha2 = "si", Alpha3 = "svn", Name = "Slovenia" },
            new Iso3166Country { IsoId = 90, Alpha2 = "sb", Alpha3 = "slb", Name = "Solomon Islands" },
            new Iso3166Country { IsoId = 706, Alpha2 = "so", Alpha3 = "som", Name = "Somalia" },
            new Iso3166Country { IsoId = 710, Alpha2 = "za", Alpha3 = "zaf", Name = "South Africa" },
            new Iso3166Country { IsoId = 239, Alpha2 = "gs", Alpha3 = "sgs", Name = "South Georgia and the South Sandwich Islands" },
            new Iso3166Country { IsoId = 728, Alpha2 = "ss", Alpha3 = "ssd", Name = "South Sudan" },
            new Iso3166Country { IsoId = 724, Alpha2 = "es", Alpha3 = "esp", Name = "Spain" },
            new Iso3166Country { IsoId = 144, Alpha2 = "lk", Alpha3 = "lka", Name = "Sri Lanka" },
            new Iso3166Country { IsoId = 729, Alpha2 = "sd", Alpha3 = "sdn", Name = "Sudan" },
            new Iso3166Country { IsoId = 740, Alpha2 = "sr", Alpha3 = "sur", Name = "Suriname" },
            new Iso3166Country { IsoId = 744, Alpha2 = "sj", Alpha3 = "sjm", Name = "Svalbard and Jan Mayen" },
            new Iso3166Country { IsoId = 752, Alpha2 = "se", Alpha3 = "swe", Name = "Sweden" },
            new Iso3166Country { IsoId = 756, Alpha2 = "ch", Alpha3 = "che", Name = "Switzerland" },
            new Iso3166Country { IsoId = 760, Alpha2 = "sy", Alpha3 = "syr", Name = "Syrian Arab Republic" },
            new Iso3166Country { IsoId = 158, Alpha2 = "tw", Alpha3 = "twn", Name = "Taiwan, Province of China" },
            new Iso3166Country { IsoId = 762, Alpha2 = "tj", Alpha3 = "tjk", Name = "Tajikistan" },
            new Iso3166Country { IsoId = 834, Alpha2 = "tz", Alpha3 = "tza", Name = "Tanzania, United Republic of" },
            new Iso3166Country { IsoId = 764, Alpha2 = "th", Alpha3 = "tha", Name = "Thailand" },
            new Iso3166Country { IsoId = 626, Alpha2 = "tl", Alpha3 = "tls", Name = "Timor-Leste" },
            new Iso3166Country { IsoId = 768, Alpha2 = "tg", Alpha3 = "tgo", Name = "Togo" },
            new Iso3166Country { IsoId = 772, Alpha2 = "tk", Alpha3 = "tkl", Name = "Tokelau" },
            new Iso3166Country { IsoId = 776, Alpha2 = "to", Alpha3 = "ton", Name = "Tonga" },
            new Iso3166Country { IsoId = 780, Alpha2 = "tt", Alpha3 = "tto", Name = "Trinidad and Tobago" },
            new Iso3166Country { IsoId = 788, Alpha2 = "tn", Alpha3 = "tun", Name = "Tunisia" },
            new Iso3166Country { IsoId = 792, Alpha2 = "tr", Alpha3 = "tur", Name = "Türkiye" },
            new Iso3166Country { IsoId = 795, Alpha2 = "tm", Alpha3 = "tkm", Name = "Turkmenistan" },
            new Iso3166Country { IsoId = 796, Alpha2 = "tc", Alpha3 = "tca", Name = "Turks and Caicos Islands" },
            new Iso3166Country { IsoId = 798, Alpha2 = "tv", Alpha3 = "tuv", Name = "Tuvalu" },
            new Iso3166Country { IsoId = 800, Alpha2 = "ug", Alpha3 = "uga", Name = "Uganda" },
            new Iso3166Country { IsoId = 804, Alpha2 = "ua", Alpha3 = "ukr", Name = "Ukraine" },
            new Iso3166Country { IsoId = 784, Alpha2 = "ae", Alpha3 = "are", Name = "United Arab Emirates" },
            new Iso3166Country { IsoId = 826, Alpha2 = "gb", Alpha3 = "gbr", Name = "United Kingdom of Great Britain and Northern Ireland" },
            new Iso3166Country { IsoId = 840, Alpha2 = "us", Alpha3 = "usa", Name = "United States of America" },
            new Iso3166Country { IsoId = 581, Alpha2 = "um", Alpha3 = "umi", Name = "United States Minor Outlying Islands" },
            new Iso3166Country { IsoId = 858, Alpha2 = "uy", Alpha3 = "ury", Name = "Uruguay" },
            new Iso3166Country { IsoId = 860, Alpha2 = "uz", Alpha3 = "uzb", Name = "Uzbekistan" },
            new Iso3166Country { IsoId = 548, Alpha2 = "vu", Alpha3 = "vut", Name = "Vanuatu" },
            new Iso3166Country { IsoId = 862, Alpha2 = "ve", Alpha3 = "ven", Name = "Venezuela, Bolivarian Republic of" },
            new Iso3166Country { IsoId = 704, Alpha2 = "vn", Alpha3 = "vnm", Name = "Viet Nam" },
            new Iso3166Country { IsoId = 92, Alpha2 = "vg", Alpha3 = "vgb", Name = "Virgin Islands (British)" },
            new Iso3166Country { IsoId = 850, Alpha2 = "vi", Alpha3 = "vir", Name = "Virgin Islands (U.S.)" },
            new Iso3166Country { IsoId = 876, Alpha2 = "wf", Alpha3 = "wlf", Name = "Wallis and Futuna" },
            new Iso3166Country { IsoId = 732, Alpha2 = "eh", Alpha3 = "esh", Name = "Western Sahara" },
            new Iso3166Country { IsoId = 887, Alpha2 = "ye", Alpha3 = "yem", Name = "Yemen" },
            new Iso3166Country { IsoId = 894, Alpha2 = "zm", Alpha3 = "zmb", Name = "Zambia" },
            new Iso3166Country { IsoId = 716, Alpha2 = "zw", Alpha3 = "zwe", Name = "Zimbabwe" },
        ];
    }
}
